### ISSUE TITLE
Check that emails will go to IAs reliably

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#465]
We need to ensure we have tests around sending IAs. These should include testing with:
1.   Gaps in emails
2.   Other minor errors which could prevent the IAs from being sent

**Comment by JeremykJAC** [comment]
- Our plan here is currently to add validation when email addresses are being entered
- We are just awaiting to hear back on other know issues

**Comment by HalcyonJAC** [comment]
- [ ] Admin - When editing an independent assessor (see screenshot below) the email field should be validated to check that the email entered is in a valid format.

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/acdca97a-dc1b-4a97-8faa-51b5c767078c)

**Comment by HalcyonJAC** [comment]
Note: The email address of assessors is already validated in the Apply portal, (see screenshot below), it just appears to be the admin portal that is missing the validation:

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/efdd2baa-95b8-4031-861c-a8546ba76853)

**Comment by HalcyonJAC** [comment]
- [ ] When sending assessment requests, the system should first check that all IA email addresses are valid and if any are found that are not an error should be returned instead of sending the emails out.
  - Note: The error should indicate the invalid email address(es)
- [ ] When sending assessment reminders, same as above
