### ISSUE TITLE
Monitor and optimise our usage of Google Cloud Platform

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#471]
Now that we've built out the essentials of the digital platform our focus needs to cover monitoring and optimising our usage of Google Cloud Platform, in particular Firebase services.

Optimising how we read, write and store data can have a big effect on how much we are billed.

**Comment by KateMJAC** [comment]
Assigned to Halcyon in the March WO.

**Comment by HalcyonJAC** [comment]
Backups of the production database have been kept since Dec 2019.

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/4ab0bf38-8288-4937-9eda-2e83e83567c2)
 
Cloud storage use has been increasing steadily because backup history is not being truncated at present.
 
![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/1dc7bace-88a3-4324-b39d-a6054bfa8ea4)

Current costs are minimal. Main cost is Cloud Firestore but that is based on the bandwidth usage of the platform. Unless the system has a big increase in end-users or inbound connections or something, I would not expect that to change much.

Current costs for cloud storage (where database backups are kept) are minimal, however backups are only being taken once a day at present, at 23:00. Increasing this to hourly backups is an option but will increase the cloud storage costs (x24). If that option is to be taken, to make that sustainable, perhaps the JAC could truncate some of the backup history (i.e. to 30 days). Note: This is not just a cost issue but a Disaster Recovery / Business Continuity question.
 
![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/29656ac8-d5b9-4499-babf-037bb43ce8bd)

**Comment by HalcyonJAC** [comment]
Hi guys

I'm not sure if there's actual code changes that should be made as part of this task or not but perhaps someone could take a look at the above findings.

@warrensearle I think this issue could be linked to the changes you are going to make to the databsae backup routine. Perhaps it would be worth merging it into an Epic ?

**Comment by warrensearle** [comment]
@HalcyonJAC agreed there is a larger epic of work around backup, restore and disaster recovery. Am sure we already have an epic for this so will post link here we can add to [ TBC - link to disaster recovery epic ]

This task around monitoring and optimising our usage of GCP is really an ongoing open-ended one. We should:
- [x] check how things are now
- [x] make recommendations for things to fix now
- [ ] make suggestions for things to watch out for (e.g. in firestore are we doing too many reads vs writes or vice versa? be good to know where the current charge is coming from)
- [ ] set up any available alerts so we are aware of spikes in usage & charges
- [ ] repeat regularly (e.g. on a monthly basis)

**Comment by KateMJAC** [comment]
Hello @warrensearle and @HalcyonJAC, am I right in thinking that this ticket has now been completed and can be closed? 

I can see that some ongoing work has dropped out of it. I'm happy for that to be ticketed.

**Comment by KateMJAC** [comment]
Hello @HalcyonJAC does this work provide a level of virus/malware scanning through Google Cloud? I'm trying to establish whether a seperate ticket is needed to specifically address the risk of malicious files being uploaded onto the platform.

**Comment by KateMJAC** [comment]
Hello @warrensearle and @HalcyonJAC  am I right in thinking that this ticket has now been completed and can be closed?

I can see that some ongoing work has dropped out of it. I'm happy for that to be ticketed.
