### ISSUE TITLE
Vulnerability - npm audit

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/digital-platform#532]

**Comment by HalcyonJAC** [comment]
found 4004 vulnerabilities (1 low, 86 moderate, 3917 high) in 1508 scanned packages

all but 8 of the vulnerabilities have been fixed. 

All but 1 of these outstanding issues can be fixed by updating `firebase-tools` by 1 major version.

The other issue is of no concern as it is in a test framework not executed on the prod environment, and it a prototype pollution error so only a concern at runtime.

**Comment by HalcyonJAC** [comment]
- [x] Update `firebase-tools` package
- [x] Check that digital platform still compiles without error
