### ISSUE TITLE
Custom report- Data Issues on Live Platform

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#672]
**The Why**
To allow the Selection exercise team to create a custom report to meet exercise need.

When the Selection exercise team go on the report menu and click on custom report. They can filter any part of candidates application they want to create a report on. The selection exercise team filtered by candidates Full Name, Jurisdiction and Location preference. However the data was displayed (Blank) incorrectly on the live platform.![Capture.PNG155.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/b9b32e0f-0ad7-4575-81d3-ee7da0f64ca0)

I tested this by logging on to admin-staging and filtered the  report by candidates Full Name, Jurisdiction and location preference. The candidates data was displayed correctly on the admin-staging ![Capture.PNG154.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/1501fc59-9f10-4713-8cf1-0f3cfaed6c0d) 

**The Expected**

The Admin should be able click on custom report and select different columns that they will like to see on the report. The live platform should display all the columns that was selected by the admin correctly on screen and also in the download

**Comment by HalcyonJAC** [comment]
Note: Joy used exercise 66 on production and exercise 432 on staging

**Comment by HalcyonJAC** [comment]
I compared applications in the staging database and the production database. The `jurisdictionPreferences` and `locationPreferences` fields are present in the staging database and are not in the production database.

See screenshots below for example:

This explains why the data is not displayed when creating a custom report on production. The question now is why is the data missing on production...?

(Staging)

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/4d6c77be-f8f2-4805-9ffe-33851db312a4)


(Production)

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/35a73fa3-faea-47c6-9773-7601c0bbb044)

**Comment by HalcyonJAC** [comment]
Sharon found the same problem with exercise JAC00070 so I checked this one out too:

It turns out that sometimes a candidate's jurisdiction preference is stored as a string, sometimes more than one choice is stored (as an array of strings). See the 2 screenshots below for example:

- develop -
![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/71560a77-383b-41d6-9e4d-b2c7855b51be)

- production -
![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/5f8d62ce-5f70-499a-9711-c2956e08618c)

This is what causes the bug where sometimes True or False is displayed instead of their chosen preferences.

The front-end code expects a string, not an array.

There is a function in the digital platform called `getApplicationData` which is called each time the end-user adds or removes a column from the custom report. The `getApplicationData` function needs updating so that for the jurisdiction preferences field and location preferences field it will cater for simple strings and arrays also.

The problem is that I can't find the code for the `getApplicationData` function anywhere in the digtal platform repo...


- (Blank) means there is no data / the candidate did not specify any preference
- T
